name: Deployment pipline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check for linting errors
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start the server
        run: npm run start & sleep 5
      - name: Wait for server
        run: |
          retries=0
          until curl -s http://localhost:8080 > /dev/null || [ $retries -ge 30 ]; do
          echo "Waiting for server to be ready... Attempt $((retries+1))"
          retries=$((retries+1))
          sleep 2
          done
          if [ $retries -ge 30 ]; then
          echo "Server failed to start after 30 attempts."
          exit 1
          fi
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
      - name: Deploy to render
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_KEY }}?key=${{ secrets.RENDER_API_KEY }}
