name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test_on_deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start the server
        run: npm run start
      - name: Run Playwright tests
        run: npm run test:e2e
